### ISSUE TITLE
Please update this project/npm to be in sync with the original project's ('hue-hacking') functionality

### ISSUE THREAD

**Issue by 4ch1m** [bjohnso5/hue-hacking-npm#2]
Hi there,

it would be awesome if we could get an updated version of this npm-module which contains the latest fixes/additions from @benknight.

Especially this one:
https://github.com/bjohnso5/hue-hacking/commit/6739545855fa4c03c5a093135a5fb41ecbf92108

I need this new function ...
`
CIE1931ToHex : function (x, y, bri) {
`
... which is not available in the current version of this project/npm.

Thanks!

**Comment by bjohnso5** [comment]
Hi 4ch1m,

I did some manual fuddling and ported over Ben Knight's PR changes from hue-hacking... had to bump the patch version a couple of times (apparently I managed to get up to 0.0.9 published without changing the package.json locally). 

Please try v0.0.10 on npm - you should be able to access the colors module through the hue object.

```javascript
var hue = require('hue-hacking-npm');
hue.colors.CIE931ToHex(...);
```

**Comment by 4ch1m** [comment]
We're nearly there. :)

Referencing the CIE1931ToHex()-method works fine now.

But I still get errors during execution:

> xyPoint is not defined ReferenceError: xyPoint is not defined
>     at getClosestPointToPoint (.../node_modules/hue-hacking-node/lib/hue-colors.js:180:52)

Something must have been lost when porting the code from the original project to this one.

Here we have...

```
    getClosestPointToPoint = function (A, B, P) {
        // Color is unreproducible, find the closest point on each line in the CIE 1931 'triangle'.
        var pAB = getClosestPointToLine(Red, Lime, xyPoint),
            pAC = getClosestPointToLine(Blue, Red, xyPoint),
            pBC = getClosestPointToLine(Lime, Blue, xyPoint),
            ...
```

(This is where it breaks, because 'xyPoint' is not defined/passed in the method-header.)

And this is how it looks in the original...
(https://github.com/bjohnso5/hue-hacking/blob/master/src/colors.js)

```
    getClosestPointToPoint = function (xyPoint) {
        // Color is unreproducible, find the closest point on each line in the CIE 1931 'triangle'.
        var pAB = getClosestPointToLine(Red, Lime, xyPoint),
            pAC = getClosestPointToLine(Blue, Red, xyPoint),
            pBC = getClosestPointToLine(Lime, Blue, xyPoint),
            ...
```

I hope you can fix this with less effort.
Otherwise let me know if I can help in any way.

This package really offers great and easy-to-use methods for color-conversions when working with the Philips Hue system.

Thank you, Bryan.

**Comment by bjohnso5** [comment]
I'll be unavailable for most of the day today (and my hue lights have been
put away for a while).

If you want to fork the project and take a stab at making the fix you need,
pull requests are always welcome.

Cheers,

Bryan

**Comment by bjohnso5** [comment]
I'm confident I've squashed that bug you ran into. Please try v0.0.11 from npm.

**Comment by 4ch1m** [comment]
Yes, it's working fine now! 👍 
Again... thanks a lot, Bryan. :)
