### ISSUE TITLE
Referenced main-file in package.json not distributed in package

### ISSUE THREAD

**Issue by 4ch1m** [bjohnso5/hue-hacking-npm#21]
Hi there,
I'm using "hue-hacking-npm" as a dependency in my [project](https://github.com/4ch1m/huElectron).
Everything worked fine in the past.
However, with the latest updates of some of my other frameworks (Electron, etc.) I now get the following error on startup:
```
Cannot find module ... node_modules/hue-hacking-node/dist/index.js'. Please verify that the package.json has a valid "main" entry.
```
I guess that's because "hue-hacking-npm" doesn't distribute the dist-folder itself, but the main-file being referenced in package.json lies in that folder.
```
...
  "description": "Utility to control Philips Hue light bulbs",
  "main": "dist/index.js",
...
```
Is there a chance that could be fixed with an upcoming release? :smiley: 
Thanks a lot!

**Comment by bjohnso5** [comment]
Apologies for not noticing that I had an open issue for so long - it looks like I may have managed to break the package with one of the updates, and you're correct that the dist folder no longer seems to be published. I'll try to fix it up shortly (although I imagine you've moved on from this library in the meantime).

**Comment by bjohnso5** [comment]
[version 1.7.0](https://www.npmjs.com/package/hue-hacking-node?activeTab=code) has just been published that removes a bunch of superfluous packages and should now properly contain the `dist/index.js` file that the package.json points to.

**Comment by bjohnso5** [comment]
I'm going to close this as I haven't heard back - please do let me know if the issue is not solved!
