### ISSUE TITLE
Do the light indexes match?

### ISSUE THREAD

**Issue by chmac** [bjohnso5/hue-hacking-npm#7]
Here's the `getLamps()` code:

https://github.com/bjohnso5/hue-hacking-npm/blob/db881602412d0274d5b2b255fdfc9e34404e3325/src/hue-node.ts#L585-L589

In the last line, the returned data is converted from an object into an array. The object I see in my tests looks like:

```
{
"1": Lamp,
"2": Lamp,
"3": Lamp
}
```

But the resulting array is zero indexed and so to be able to call `setColor` I need a 1 based index. So I end up adding 1 to the index. I'm wondering if this is deliberate. I assume that the Hue API will never skip number, nor return indexes out of sequence, but I can't see any way to actually get the index out of the `getLamps()` response. Would you be open to a PR which added a field called `index` to the `Lamp` type?

**Comment by chmac** [comment]
PS> I forgot to say, most importantly, thanks for this package. Makes working with the Hue bridge from typescript a breeze!

**Comment by bjohnso5** [comment]
Hey Callum, sorry for the late response.

The numeric key returned in the response is referred to as an index in my codebase, but it's more like an ID in the official Hue API docs. You need to keep track of the numbers returned by the bridge, as that's how the bridge actually addresses the lamps. I'd be OK with adding it to the Lamp object definition if it would help you out (I have to admit that my bulbs are tucked away in a closet and aren't currently in use).

I'll take a look at your PR when you've got it all set for review.

Also, thanks for the kind words, I'm glad you've had success using the library!
